use_frameworks!

target 'XXModel_Example' do
  pod 'XXModel', :path => '../'

  target 'XXModel_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
